version: "3"

services:
  project:
    build: .
    restart: always
    ports:
      - 3000:3000

  db:
    container_name: pg_db
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
      volumes:
        ./postgres_data:/var/lib/postgresql/data/
      ports:
        "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: noemail@noemail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"