version: "3"

services:
  project:
    build: .
    restart: always
    ports:
      - 3000:3000
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: database